### ISSUE TITLE
[US] Dev environment set-up

### ISSUE THREAD

**Issue by JaqiKal** [ci-companeros/lazydog#14]
**Statement**:

As a **developer**, I can **set up my dev environment** so that **I have all the tools and configurations required to start coding**.

**Acceptance Criteria**:

- [x] Developers can clone the project repository and set up a local or cloud-based development environment.
- [x] Having a venv set up.
- [x] All team members have npm, Python, Django, and PostgreSQL installed.
- [x] Initial Environment variables are set.

**Tasks**:

- [x] Set up Git and create branches for each feature.
- [x] Install npm, and Tailwind CSS for the frontend.
- [x] Set up the Django backend with PostgreSQL.
- [x] Configure the .env file for storing sensitive credentials.

**Belonging to Epic**: Project Setup & Initialization  
**Belonging to Feature**: Setup Environment
**Belonging to Theme**: Foundation Tasks
