### ISSUE TITLE
[US] Backend Framework Setup

### ISSUE THREAD

**Issue by JaqiKal** [ci-companeros/lazydog#16]
**Statement**:

As a **developer**, I can **set up the backend framework** so that **I create a robust foundation for the application**.

**Acceptance Criteria**:

- [x] The Django REST Framework is installed and configured.
- [x] Basic project structure is established.
- [x] Admin account configured.

**Tasks**:

- [x] Install Django and Django REST Framework.
- [x] Create a new Django project and install necessary apps.
- [x] Create Admin.
- [x] Configure settings for the development environment.

**Belonging to Epic**: Project Setup & Initialization  
**Belonging to Feature**: Setup Backend  
**Belonging to Theme**: Foundation Tasks

**Comment by EVondrus** [comment]
Done!
