### ISSUE TITLE
[US] Database Integration

### ISSUE THREAD

**Issue by JaqiKal** [ci-companeros/lazydog#18]
**Statement**:

As a **developer**, I can **integrate the backend with PostgreSQL** so that **data is stored and retrieved efficiently**.

**Acceptance Criteria**:

- [x] PostgreSQL is configured as the database for the application.
- [x] Data operations are performed successfully using the ORM.

**Tasks**:

- [x] Set up PostgreSQL database and connect it to the Django application.
- [x] Test data retrieval and storage operations.

**Belonging to Epic**: Database & Backend Design  
**Belonging to Feature**: Setup Backend  
**Belonging to Theme**: Database & Backend

**Comment by EVondrus** [comment]
Great Job!
