### ISSUE TITLE
[US] Create Models

### ISSUE THREAD

**Issue by JaqiKal** [ci-companeros/lazydog#19]
**Statement**:

As a **developer**, I can **create models for the application** so that **I can manage data effectively**.

**Acceptance Criteria**:

- [x] Models are defined according to ERD.
- [x] Database migrations are created and applied.

**Tasks**:

- [x] Define models according to ERD.
- [x] Create and apply migrations to set up the database schema.
- [x] Add User model  - We use Django all auth as is.
- [x] Add Resource_item  - JJ
- [x] Add Comment - NH
- [x] Add Rating  - JJ
- [x] Add Category  - JJ
- [x] Add Tag  - JK
- [x] Add Flag - EV
- [x] Add Bookmark -JK
- Add Notification  => Moved to [US#112](https://github.com/ci-companeros/lazydog/issues/112)
- Add Audit   => Moved to [US#111](https://github.com/ci-companeros/lazydog/issues/111)

**Belonging to Epic**: Database & Backend Design  
**Belonging to Feature**: Setup Backend  
**Belonging to Theme**: Database & Backend

**Comment by JaqiKal** [comment]
Add Notification => Moved to https://github.com/ci-companeros/lazydog/issues/112
Add Audit => Moved to https://github.com/ci-companeros/lazydog/issues/111

This model is closed as per decision at Huddle 250531.
