### ISSUE TITLE
[US] Featured Resources - Home Page

### ISSUE THREAD

**Issue by JaqiKal** [ci-companeros/lazydog#34]
**Statement**:

As a **user** I can **view a carousel on the homepage** so that **I can quickly view featured resources and call-to-action buttons**.

**Acceptance Criteria**:

- [ ] The carousel displays the top 5 rated resources, YouTube clips, best contributions, and more.
- [ ] Each slide has a call-to-action button linking to relevant pages.
- [ ] The carousel is responsive and user-friendly.

**Tasks**:

- [ ] Create a carousel component for the homepage.
- [ ] Integrate call-to-action buttons with links.
- [ ] Style the carousel for smooth transitions and responsiveness.

**Belonging to Epic**: Home Page & Resource Listing  
**Belonging to Feature**: Home Page  
**Belonging to Theme**: Frontend Structure
