### ISSUE TITLE
[US] Category Section - Home Page

### ISSUE THREAD

**Issue by JaqiKal** [ci-companeros/lazydog#35]
**Statement**:

As a **user** I can **view categories on the homepage** so that **I can easily find resources related to my interests**.

**Acceptance Criteria**:

- [ ] The category section displays a grid of all available categories.
- [ ] Each category is clickable and leads to a filtered resource page.
- [ ] Categories are visually distinct and engaging.

**Tasks**:

- [ ] Design the layout for the category section on the homepage according to blueprint.
- [ ] Create a component to display all available categories.
- [ ] Implement links for each category that redirect to the respective resource page.
- [ ] Style the category section for a modern and appealing look.

**Belonging to Epic**: Home Page & Resource Listing  
**Belonging to Feature**: Home Page  
**Belonging to Theme**: Frontend Structure
