### ISSUE TITLE
[US] Dashboard - Overview

### ISSUE THREAD

**Issue by JaqiKal** [ci-companeros/lazydog#47]
**Statement**:

As a **logged in user**, I can **view and manage my dashboard** so that **I can keep track of my contributions, comment and rating activity**.

**Acceptance Criteria**:

- [ ] Users can view their contribution, comment, and rating history.
- [ ] Users have options to edit or delete their contributions.
- [ ] The dashboard encourages users to contribute more.

**Tasks**:

- [ ] Design the user dashboard with tabs for contributions, comments, and ratings according to wireframe.
- [ ] Implement Read, Update, Delete (RUD) functionality for managing contributions, comments, and ratings.
- [ ] Add motivational messages to encourage further contributions.

**Belonging to Epic**: User Dashboard  
**Belonging to Feature**: User Dashboard  
**Belonging to Theme**: Core Features
