### ISSUE TITLE
[US] Comment Management

### ISSUE THREAD

**Issue by JaqiKal** [ci-companeros/lazydog#49]
**Statement**:

As a **logged in user**, I can **view my comments** so that **I can manage my feedback on resources**.

**Acceptance Criteria**:

- [ ] Users can view a list of their comments on the dashboard.
- [ ] Each comment displays relevant details (e.g., resource title, comment text).
- [ ] Users can edit or delete their comments directly from the dashboard.

**Tasks**:

- [ ] Design the comments tab in the user dashboard according to the wireframe.
- [ ] Implement the functionality to fetch and display user comments.
- [ ] Add RUD functionality for managing comments.

**Belonging to Epic**: User Dashboard  
**Belonging to Feature**: User Account Mgmt
**Belonging to Theme**: Core Features
