### ISSUE TITLE
[US] Dashboard Overview

### ISSUE THREAD

**Issue by JaqiKal** [ci-companeros/lazydog#54]
**Statement**:

As an **admin**, I can **manage submitted resources and comments, manage user accounts and flagged content** so that **I can ensure a safe and respectful community and the quality of the content on the platform**.

**Acceptance Criteria**:

- [ ] Admins can view a list of all registered users with their roles (admin/user) and status (active/inactive).
- [ ] Admins can promote or demote users to/from admin status.
- [ ] Admins can deactivate or delete user accounts based on flagging history.
- [ ] Admins can view flagged resources and comments to take appropriate action.

**Tasks**:

- [ ] Design the admin dashboard according to the wireframe.

**Belonging to Epic**: Admin Dashboard & Platform Moderation  
**Belonging to Feature**: Admin Dashboard  
**Belonging to Theme**: Advanced Features
