### ISSUE TITLE
[US] User Account Management

### ISSUE THREAD

**Issue by JaqiKal** [ci-companeros/lazydog#56]
**Statement**:

As an **admin**, I can **manage user accounts** so that **I can moderate user activities and maintain platform security**.

**Acceptance Criteria**:

- [ ] Admins can deactivate user accounts to temporarily restrict access.
- [ ] Admins can delete user accounts permanently based on flagging history.

**Tasks**:

- [ ] Add buttons to deactivate or delete user accounts.
- [ ] Implement logic to handle account deactivation and deletion.
- [ ] Notify users by email.

**Belonging to Epic**: Admin Dashboard & Platform Moderation  
**Belonging to Feature**: Admin Dashboard  
**Belonging to Theme**: Advanced Features
