### ISSUE TITLE
[US] Confirmation Pages

### ISSUE THREAD

**Issue by JaqiKal** [ci-companeros/lazydog#69]
**Statement**:

As a **user**, I can **receive confirmation pages after completing significant actions (such as submitting a contribution)** so that I can **be assured that my action was successful with a cheerful message and know what to expect next**.

**Acceptance Criteria**:

- [ ] The confirmation page should clearly indicate that the action was completed.
- [ ] Users should have the option to navigate back to the previous page or return to the homepage.

**Tasks**:

- [ ] Design a visually clear and informative confirmation page layout.
- [ ] Include a prominent message indicating the successful completion of the action.
- [ ] Add buttons for users to navigate back to the previous page or return to the homepage.

**Belonging to Epic**: Error & Confirmation Pages  
**Belonging to Feature**: Error & Confirmation Pages  
**Belonging to Theme**: UI Enhancements
